{
 "title": "K8s Container",
 "description": "Summary metrics about containers running on Kubernetes nodes.",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "heili-kubernetes-datasource" },
   { "name": "ds", "query": "datasource" },
   { "name": "datasource", "query": "elasticsearch" },
   { "name": "node", "query": "node" },
   { "name": "namespace", "query": "namespace" },
   { "name": "pod", "query": "pod $namespace" }
  ]
 },
 "panels": [
  { "title": "Pod Filtering", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "heili-kubernetes-podnav-panel", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "description": "Total memory usage of containers across a cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.pod_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "fields.memory_usage_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name: kubernetes_pod_container && tags.node_name: $node && tags.namespace: $namespace && tags.pod_name: $pod",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "cpu" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.pod_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "fields.cpu_usage_nanocores",
       "id": "1",
       "inlineScript": "_value / 1000000000",
       "meta": {},
       "settings": { "script": { "inline": "_value / 1000000000" } },
       "type": "sum"
      }
     ],
     "query": "name: kubernetes_pod_container && tags.node_name: $node && tags.namespace: $namespace && tags.pod_name: $pod",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Traffic (Inbound)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.pod_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "fields.tx_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name: kubernetes_pod_network && tags.node_name: $node && tags.namespace: $namespace && tags.pod_name: $pod",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Traffic (Outbound)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.pod_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "fields.rx_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name: kubernetes_pod_network && tags.node_name: $node && tags.namespace: $namespace && tags.pod_name: $pod",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk usage - rootfs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.pod_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "fields.rootfs_used_bytes",
       "id": "1",
       "inlineScript": "_value * 100 / doc['fields.rootfs_capacity_bytes'].value",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value * 100 / doc['fields.rootfs_capacity_bytes'].value"
        }
       },
       "type": "avg"
      }
     ],
     "query": "name: kubernetes_pod_container && tags.node_name: $node && tags.namespace: $namespace && tags.pod_name: $pod",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk usage - mounted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{tags.pod_name}} - {{tags.volume_name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.volume_name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "tags.pod_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "fields.used_bytes",
       "id": "1",
       "inlineScript": "_value * 100 / doc['fields.capacity_bytes'].value",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value * 100 / doc['fields.capacity_bytes'].value"
        }
       },
       "type": "avg"
      }
     ],
     "query": "name: kubernetes_pod_volume && tags.node_name: $node && tags.namespace: $namespace && tags.pod_name: $pod",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}