{
 "title": "K8s StatefulSet",
 "description": "StatefulSet overview for Kubernetes deploys.",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "heili-kubernetes-datasource" },
   { "name": "ds", "query": "datasource" },
   { "name": "datasource", "query": "elasticsearch" },
   { "name": "node", "query": "node" },
   { "name": "namespace", "query": "namespace" },
   { "name": "statefulset", "query": "statefulset $namespace" }
  ]
 },
 "panels": [
  {
   "title": "StatefulSet Replicas - Desired",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name: kube_statefulset_status_replicas && tags.namespace: $namespace && tags.host: $node && tags.statefulset: $statefulset",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "StatefulSet Replicas - Current",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name: kube_statefulset_status_replicas_current && tags.namespace: $namespace && tags.host: $node && tags.statefulset: $statefulset",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "StatefulSet Replicas - Up-to-date",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name: kube_statefulset_status_replicas_updated && tags.namespace: $namespace && tags.host: $node && tags.statefulset: $statefulset",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{tags.statefulset}}.{{tags.namespace}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.statefulset",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "tags.namespace",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name: kube_statefulset_status_replicas && tags.namespace: $namespace && tags.host: $node && tags.statefulset: $statefulset",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Generations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{tags.statefulset}}.{{tags.namespace}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.statefulset",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "tags.namespace",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name: kube_statefulset_status_observed_generation && tags.namespace: $namespace && tags.host: $node && tags.statefulset: $statefulset",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}