{
 "title": "K8s Jobs",
 "description": "Overview for Kubernetes Jobs.",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "query": "heili-kubernetes-datasource" },
   { "name": "ds", "query": "datasource" },
   { "name": "datasource", "query": "elasticsearch" },
   { "name": "node", "query": "node" },
   { "name": "namespace", "query": "namespace" }
  ]
 },
 "panels": [
  {
   "title": "Total Active Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name: kube_job_status_active && tags.host: $node && tags.namespace: $namespace",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Active CronJobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name: kube_cronjob_status_active && tags.host: $node && tags.namespace: $namespace",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name: kube_job_status_failed && tags.host: $node && tags.namespace: $namespace",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Succeeded Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.gauge",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name: kube_job_status_succeeded && tags.host: $node && tags.namespace: $namespace",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}